import { DIFFICULT_EASY, DIFFICULT_ENDLESS, DIFFICULT_HARD, DIFFICULT_MEDIUM, DIFFICULT_SANDBOX } from '../constants/game-units.constants';

export enum LevelsEnum {
    DAYTIME = 'DAYTIME',
    SUNSET = 'SUNSET',
    NIGHT = 'NIGHT',
    KELLY_DRIVE = 'KELLY_DRIVE',
    RITTEN_HOUSE = 'RITTEN_HOUSE',
    CHINA_TOWN = 'CHINA_TOWN',
}
export enum DifficultyEnum {
    EASY = DIFFICULT_EASY,
    MEDIUM = DIFFICULT_MEDIUM,
    HARD = DIFFICULT_HARD,
    ENDLESS = DIFFICULT_ENDLESS,
    SANDBOX = DIFFICULT_SANDBOX,
}
