export enum Objects {
    ANVIL = 'anvil',
    APPLE = 'apple',
    BIGPOO = 'bigpoo',
    BOTTLE = 'bottle',
    CHINESEFOOD = 'chinesefood',
    CONE = 'cone',
    CRATER = 'crater',
    FLOWERS = 'flowers',
    GHOST = 'ghost',
    HURDLE = 'hurdle',
    BELL = 'bell',
    PIGEON = 'pigeon',
    POOP = 'poop',
    POOPINGPIGEON = 'pooping-pigeon',
    STAND = 'stand',
    TOMB = 'tomb',
    TOURIST = 'tourist000',
    TRASHCAN = 'trashcan',
    WIND = 'wind',
    CHEESESTEAK = 'cheesesteak',
    GLOVES = 'gloves',
}
