export enum PreferencesEnum {
    AUDIO_ON = 'AUDIO_ON',
    EFFECTS_ON = 'EFFECTS_ON',
    TOTAL_POINTS = 'TOTAL_POINTS',
    TUTORIAL = 'TUTORIAL',
    PROGRESSION = 'PROGRESSION',
    KNOWN_USER = 'KNOWN_USER',
}
